update

diff --git a/bin/sync-repo b/bin/sync-repo
--- a/bin/sync-repo
+++ b/bin/sync-repo
@@ -29,11 +29,10 @@ create_commit () {
 }
 
 push_commit () {
-  echo
-# git push -u "$remote" ${branch:+"$branch"} || {
-#   echo "error while pushing changes to remote in $(basename "$(pwd)") repo."
-#   exit 7
-# }
+  git push -u "$remote" ${branch:+"$branch"} || {
+    echo "error while pushing changes to remote in $(basename "$(pwd)") repo."
+    exit 7
+  }
 }
 
 if [ -z "$repo" ]; then
