auto sync (vcs-sync: 2024-01-12 13:03)

diff --git a/bin/sync-repo b/bin/sync-repo
--- a/bin/sync-repo
+++ b/bin/sync-repo
@@ -29,10 +29,11 @@ create_commit () {
 }
 
 push_commit () {
-  git push -u "$remote" ${branch:+"$branch"} || {
-    echo "error while pushing changes to remote in $(basename "$(pwd)") repo."
-    exit 7
-  }
+  echo
+# git push -u "$remote" ${branch:+"$branch"} || {
+#   echo "error while pushing changes to remote in $(basename "$(pwd)") repo."
+#   exit 7
+# }
 }
 
 if [ -z "$repo" ]; then
